### ISSUE TITLE
How to make the inference of GPT-J run on multiple GPU ? 

### ISSUE THREAD

**Issue by 22Mukesh22** [mallorbc/Finetune_LLMs#10]
I am trying to run the GPT-J inference over multiple GPU so that for big max_length I can get the result within 10 to 20 sec . But it takes to long to generate result . I am having 8GPU. But I am able to use only 1 .

**Comment by mallorbc** [comment]
This repo has very basic examples for inference in the inference folder.  If you want to use DeepSpeed MII, change ```tensor_parallel``` from 1 to 8 in deploy.py

**Comment by mallorbc** [comment]
Closing.  Feel free to reopen if you still have issues.
