### ISSUE TITLE
 DeepSpeedZeRoOffload initialize [end]

### ISSUE THREAD

**Issue by arain60gb** [mallorbc/Finetune_LLMs#12]
![image](https://user-images.githubusercontent.com/68852604/211685056-e1ae8349-4f84-4ace-abee-1593e7b4fe8a.png)

**Comment by mallorbc** [comment]
This is likely due to running out of RAM.  Though I can not tell without more information.

**Comment by arain60gb** [comment]
hey @mallorbc , Thanks your previous comment was helpful however, after finetuning gpt-j-6b model the file size is 24GB which is split into to 12GB files [Which is not cost effective in terms of hosting the model]. where as when i finetune 2.7B model, the size is reduce to 5GB which is the expected behaviour of deepspeed. kindly guide me how to reduce the size of 24GB to 12GB.Thanks
![image](https://user-images.githubusercontent.com/68852604/211931343-557d4c74-b46f-49f2-92bc-e8604728d5d4.png)

**Comment by arain60gb** [comment]
@mallorbc 
please see the logs during model training the size of the model is shown 11.77G however the final model has two files of 12G each.Any guidance to solve this issue. Thanks 
![image](https://user-images.githubusercontent.com/68852604/211936856-dffde90b-e1a6-48b4-8204-1c804de73ca5.png)

**Comment by mallorbc** [comment]
Save the model wither either fp16 or bf16.  Change the checkpoint shard size by following the steps here if you want one file for the model.
https://huggingface.co/docs/transformers/big_models#sharded-checkpoints
