### ISSUE TITLE
Sends Kill to process when trying to resume a finetune on LLaMA 7B

### ISSUE THREAD

**Issue by Pathos14489** [mallorbc/Finetune_LLMs#15]
How to replicate:
Start to finetune model, let it checkpoint, CTRL+C or kill the process in some other form, rerun the same command. It will load everything as normal, but flip out right after loading the checkpoint and give error code -9.

**Comment by mallorbc** [comment]
It takes more RAM to reload a checkpoint.  How much RAM do you have?

**Comment by ANDDigest** [comment]
Running into the same error on Google Colab Pro with 40Gb A100 and 80Gb of RAM

**Comment by mallorbc** [comment]
Likely due to RAM usage
