### ISSUE TITLE
Unable to find image 'gpt:latest' locally

### ISSUE THREAD

**Issue by csaben** [mallorbc/Finetune_LLMs#22]
After running the build_image.sh and then running run_image.sh I get the following error

```zsh
Unable to find image 'gpt:latest' locally
docker: Error response from daemon: pull access denied for gpt, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

**Comment by mallorbc** [comment]
Sounds like the ```build_image.sh``` did something weird.  Please tell me what the output is for:

```docker image ls```

and what the output is when you build the image.
