### ISSUE TITLE
RuntimeError: The expanded size of the tensor (50257) must match the existing size (0) at non-singleton dimension 0.  Target sizes: [50257].  Tensor sizes: [0]

### ISSUE THREAD

**Issue by CrackerHax** [mallorbc/Finetune_LLMs#9]
Using --model_name_or_path hivemind/gpt-j-6B-8bit

RuntimeError: The expanded size of the tensor (50257) must match the existing size (0) at non-singleton dimension 0.  Target sizes: [50257].  Tensor sizes: [0]

**Comment by yechenqiao** [comment]
I think it's because the youtube video was made in Nov 2021, the versions has changed.

This pip version set worked for me after hours of experimenting it...
pip install transformers==4.12.5 tokenizers==0.10.3 huggingface-hub==0.1.2 datasets==1.15.1

**Comment by mallorbc** [comment]
This repo does not support the 8bit GPTJ.  That is likely why.
